
export const manualFiles = [
  { name: "Intro", file: "File_00.0_Intro.md", slug: "intro" },
  { name: "Tools & Ingredients", file: "File 01.0 - Tools, Techniques & Ingredients.md", slug: "tools-and-ingredients" },
  { name: "Wood Library", file: "File 02.0 - Wood Library Complete.md", slug: "wood-library" },
  { name: "Garnish Library", file: "File 02.1 - Garnish Library Complete.md", slug: "garnish-library" },
  { name: "Recipe Index", file: "File 03.0 - Quick Reference Chart - All 50 Classic Cocktails.md", slug: "recipe-index" },
  { name: "Recipes 1-6", file: "File 03.1 - Recipes 1-6.md", slug: "recipes-1-6" },
  { name: "Recipes 7-15", file: "File 03.2 - Recipes 7-15.md", slug: "recipes-7-15" },
  { name: "Recipes 16-25", file: "File 03.3 - Recipes 16-25.md", slug: "recipes-16-25" },
  { name: "Recipes 26-38", file: "File 03.4 - Recipes 26-38.md", slug: "recipes-26-38" },
  { name: "Recipes 39-50", file: "File 03.5 - Recipes 39-50.md", slug: "recipes-39-50" },
  { name: "Adult Mocktails", file: "File 04.0 - Adult NA Mocktails Master File.md", slug: "adult-mocktails" },
  { name: "Kid-Friendly Mocktails", file: "File 05.0 - Kid-Friendly Mocktails Master File.md", slug: "kid-friendly-mocktails" },
  { name: "Smoker Devices", file: "File 06.0 - Smoker Devices Guide Complete.md", slug: "smoker-devices" },
  { name: "Smoking Techniques", file: "File 07.0 - Smoking Techniques Master Guide.md", slug: "smoking-techniques" },
  { name: "Substitutions", file: "File 08.0 - Spirit Substitution Guide.md", slug: "substitutions" },
  { name: "Glassware", file: "File 09.0 - Glassware Guide Complete.md", slug: "glassware" },
  { name: "Ice Types", file: "File 10.0 - Ice Types Guide Complete.md", slug: "ice-types" },
  { name: "Food Pairing", file: "File 11.0 - Food Pairing Complete.md", slug: "food-pairing" },
  { name: "Bitters Guide", file: "File 12.0 - Bitters & Tinctures Guide Complete.md", slug: "bitters-guide" },
  { name: "Syrups Guide", file: "File 13.0 - Syrups & Sweeteners Guide Complete.md", slug: "syrups-guide" },
  { name: "Advanced Techniques", file: "File 14.0 - Advanced Techniques Complete.md", slug: "advanced-techniques" },
  { name: "Troubleshooting", file: "File 15.0 - Troubleshooting Complete.md", slug: "troubleshooting" },
  { name: "Bar Tools", file: "File 16.0 - Bar Tools Complete.md", slug: "bar-tools"},
  { name: "Cocktail Categories", file: "File 17.0 - Cocktail Categories Complete.md", slug: "cocktail-categories"},
  { name: "Taste Profile", file: "File 18.0 - Taste Profile Guide Complete.md", slug: "taste-profile"},
  { name: "Safety Guide", file: "File 19.0 - Safety Guide Complete.md", slug: "safety-guide"},
  { name: "Quick Reference", file: "File 20.0 - Quick Reference Card Complete.md", slug: "quick-reference"},
  { name: "Shopping Guide", file: "File 21.0 - Stocking & Shopping Guide.md", slug: "shopping-guide"},
];
